---
abstract: 'Interface to compare directories.'
author:
  - unknown
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Compare-Directory
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/Manwar/Compare-Directory.git
version: '1.18'
