---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Compare-Directory
no_index:
  directory:
    - t
    - inc
requires:
  CAM::PDF: '1.52'
  File::Compare: '1.1003'
  Module::Build: '0.36'
  Readonly: '1.03'
  Test::Deep: '0'
  Test::Excel: '1.11'
  Test::More: '0'
  Text::PDF: '0'
  XML::SemanticDiff: '1.0'
version: '1.16'
